### ISSUE TITLE
Tribble fails to create github issue if issue description is too long, losing data

### ISSUE THREAD

**Issue by marienz** [arctic-hen7/tribble#4]
Trying to file an issue against Perseus that included a somewhat lengthy compiler error, clicking "create issue" resulted in a "Whoa there! Your request URL is too long. " error from Github.

This wouldn't be too bad if the browser back button worked, but it does not. The back button took me back to the "Welcome to the contributing website for Perseus!" page.

(Sorry for the wonky issue editing, I hit the wrong keyboard shortcut :sweat_smile: )

**Comment by arctic-hen7** [comment]
Ah, that's a problem! You should be able to just copy it into GH, but Tribble should stop you from submitting through the URL system if the issue is too long. This should be fairly easy to fix, provided we know how long is too long...

**Comment by marienz** [comment]
Ugh, I assumed the limit would be documented and/or POST would have a higher limit, but glancing at https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query  it does not mention either of those things... If the limit isn't documented, relying on the current value seems unwise.

Maybe make the "create issue" link open in a new tab? That'd at least circumvent any back button issues.

**Comment by arctic-hen7** [comment]
Oh yay. Good idea, let's go with that, and I'll experiment to figure out what their length limit is in practice for a warning.

**Comment by arctic-hen7** [comment]
Note that this can't actually be released until I update Tribble to use Perseus v0.4, due to underlying issues in the v0.3.6 CLI related to an upstream issue.
